import {
  ConflictException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import type {
  CreateLedgerEntry,
  LedgerEntryQuery,
  LedgerSourceType,
  TransactionType,
  UpdateLedgerEntry,
} from '@ohmypos/api-contracts';
import { PrismaService } from '../../common/prisma/prisma.service';
import { Prisma } from '../../generated/prisma/client';

/**
 * Ported from Kasync with the ERD v3 extensions: `accountId` (required),
 * `sourceType` and `sourceId`. The `userId` scoping is gone (ERD §7 note 1).
 *
 * Entries created through this module are always `sourceType = MANUAL`; the
 * SALE / PURCHASE / PAYABLE_SETTLEMENT variants are written by their own
 * modules inside a transaction in Phase 3/4/5 (Playbook §7).
 */
@Injectable()
export class LedgerEntriesService {
  constructor(private readonly prisma: PrismaService) {}

  /**
   * Creates a system-generated entry inside the CALLER'S transaction (Playbook §3,
   * §7). New modules must not write `ledger_entries` directly; they call this.
   *
   * Takes `tx`, never `this.prisma` — a Sale, a Purchase and a Settlement each
   * need the entry to commit or roll back with the rest of their flow.
   *
   * `sourceType` is never MANUAL here: MANUAL is what `create()` below produces,
   * and `update()` refuses to edit anything that is not MANUAL (TASK-003 note 7).
   */
  async createSystemEntry(
    tx: Prisma.TransactionClient,
    input: {
      accountId: string;
      categoryId: string;
      branchId: string;
      entryDate: Date;
      amount: Prisma.Decimal;
      type: TransactionType;
      sourceType: Exclude<LedgerSourceType, 'MANUAL'>;
      sourceId: string | null;
      note?: string | null;
    },
  ) {
    return tx.ledgerEntry.create({
      data: { ...input, note: input.note ?? null },
    });
  }

  async create(dto: CreateLedgerEntry) {
    await this.assertReferencesExist(
      dto.accountId,
      dto.categoryId,
      dto.branchId,
    );

    return this.prisma.ledgerEntry.create({
      data: {
        accountId: dto.accountId,
        categoryId: dto.categoryId,
        branchId: dto.branchId,
        entryDate: new Date(dto.entryDate),
        amount: new Prisma.Decimal(dto.amount),
        type: dto.type,
        note: dto.note ?? null,
        sourceType: 'MANUAL',
      },
    });
  }

  async findAll(query: LedgerEntryQuery) {
    const { page, limit, sortBy } = query;
    const skip = (page - 1) * limit;

    const entryDateFilter: Prisma.DateTimeFilter | undefined =
      query.startDate || query.endDate
        ? {
            ...(query.startDate && { gte: new Date(query.startDate) }),
            ...(query.endDate && { lte: new Date(query.endDate) }),
          }
        : undefined;

    const where: Prisma.LedgerEntryWhereInput = {
      ...(query.branchId && { branchId: query.branchId }),
      ...(query.categoryId && { categoryId: query.categoryId }),
      ...(query.accountId && { accountId: query.accountId }),
      ...(query.type && { type: query.type }),
      ...(entryDateFilter && { entryDate: entryDateFilter }),
    };

    const [data, total] = await Promise.all([
      this.prisma.ledgerEntry.findMany({
        where,
        skip,
        take: limit,
        orderBy: { [sortBy ?? 'entryDate']: 'desc' },
      }),
      this.prisma.ledgerEntry.count({ where }),
    ]);

    return {
      data,
      meta: { total, page, limit, totalPages: Math.ceil(total / limit) },
    };
  }

  async findOne(id: string) {
    const entry = await this.prisma.ledgerEntry.findUnique({ where: { id } });
    if (!entry) {
      throw new NotFoundException(`Ledger entry with ID ${id} not found`);
    }
    return entry;
  }

  async update(id: string, dto: UpdateLedgerEntry) {
    const existing = await this.findOne(id);

    if (existing.sourceType !== 'MANUAL') {
      throw new ConflictException(
        `Ledger entry ${id} was generated by a ${existing.sourceType} and cannot be edited directly`,
      );
    }

    await this.assertReferencesExist(
      dto.accountId,
      dto.categoryId,
      dto.branchId,
    );

    return this.prisma.ledgerEntry.update({
      where: { id },
      data: {
        ...(dto.accountId && { accountId: dto.accountId }),
        ...(dto.categoryId && { categoryId: dto.categoryId }),
        ...(dto.branchId && { branchId: dto.branchId }),
        ...(dto.entryDate && { entryDate: new Date(dto.entryDate) }),
        ...(dto.amount !== undefined && {
          amount: new Prisma.Decimal(dto.amount),
        }),
        ...(dto.type && { type: dto.type }),
        ...(dto.note !== undefined && { note: dto.note ?? null }),
      },
    });
  }

  async remove(id: string) {
    await this.findOne(id);

    const allocCount = await this.prisma.allocation.count({
      where: { ledgerEntryId: id },
    });
    if (allocCount > 0) {
      throw new ConflictException(
        `Cannot delete ledger entry with ${allocCount} allocation(s)`,
      );
    }

    return this.prisma.ledgerEntry.delete({ where: { id } });
  }

  /** Fails fast with a 404 rather than letting Prisma raise a foreign-key error. */
  private async assertReferencesExist(
    accountId?: string,
    categoryId?: string,
    branchId?: string,
  ) {
    const [account, category, branch] = await Promise.all([
      accountId
        ? this.prisma.account.findUnique({ where: { id: accountId } })
        : null,
      categoryId
        ? this.prisma.category.findUnique({ where: { id: categoryId } })
        : null,
      branchId
        ? this.prisma.branch.findUnique({ where: { id: branchId } })
        : null,
    ]);

    if (accountId && !account) {
      throw new NotFoundException(`Account with ID ${accountId} not found`);
    }
    if (categoryId && !category) {
      throw new NotFoundException(`Category with ID ${categoryId} not found`);
    }
    if (branchId && !branch) {
      throw new NotFoundException(`Branch with ID ${branchId} not found`);
    }
  }
}
